### PR TITLE
Update _index.html

### PR DESCRIPTION
**Pull request by logicmason**
update copyright year range

### CODE REVIEW

**Comment by PatrickJS** [comment]
You actually don't need to update the copyright year. For example look at facebook's source code and you will see the origin year

**Comment by logicmason** [comment]
It's hard for some people not to be perfectionists about these little details!

screen shot 2014-02-05 at 11 10 04 am

**Comment by PatrickJS** [comment]
such contribs

**Comment by bchu** [comment]
do you even ship?

**Pull request merged**
